CREATE TABLE IF NOT EXISTS FreeCompany (
FreeCompanyId int(20) NOT NULL, 
MasterCharacterId int(20), 
MasterCharacterName VARCHAR(32), 
FcName VARCHAR(23), 
FcTag VARCHAR(6), 
FcCredit int(20), 
FcCreditAccumu int(20), 
FcRank smallint(6), 
FcPoint int(20), 
CrestId int(20), 
CreateDate int(11), 
GrandCompanyID int(3), 
Reputation_0 int(20), 
Reputation_1 int(20), 
Reputation_2 int(20), 
FcStatus int(3), 
FcBoard varchar(193), 
MoveGcDate int(20), 
FcMotto varchar(193), 
FcVersion int(11), 
ActiveActionList_0 int(20), 
ActiveActionList_1 int(20), 
ActiveActionList_2 int(20), 
ActiveActionLeftTime_0 int(20), 
ActiveActionLeftTime_1 int(20), 
ActiveActionLeftTime_2 int(20), 
StockActionList_0 int(20), 
StockActionList_1 int(20), 
StockActionList_2 int(20), 
StockActionList_3 int(20), 
StockActionList_4 int(20), 
StockActionList_5 int(20), 
StockActionList_6 int(20), 
StockActionList_7 int(20), 
StockActionList_8 int(20), 
StockActionList_9 int(20), 
StockActionList_10 int(20), 
StockActionList_11 int(20), 
StockActionList_12 int(20), 
StockActionList_13 int(20), 
StockActionList_14 int(20),
`UPDATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`FreeCompanyId`),
KEY `index` (`MasterCharacterId`) )ENGINE=InnoDB DEFAULT CHARSET=utf8;