CREATE TABLE IF NOT EXISTS fcmember (
FreeCompanyId int(20) UNSIGNED, 
FcMemberId int(20) UNSIGNED, 
HierarchyType int(3), 
LastLogout int(11),
`UPDATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`FreeCompanyId`,`FcMemberId`),
KEY `index` (`FcMemberId`) )ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS fchierarchy (
FreeCompanyId int(20),
SortNo int(3), 
HierarchyName VARCHAR(46), 
AuthorityList int(20), 
SortNo_0 int(3), 
HierarchyName_0 VARCHAR(46), 
AuthorityList_0 int(20), 
SortNo_1 int(3), 
HierarchyName_1 VARCHAR(46), 
AuthorityList_1 int(20), 
SortNo_2 int(3), 
HierarchyName_2 VARCHAR(46), 
AuthorityList_2 int(20), 
SortNo_3 int(3), 
HierarchyName_3 VARCHAR(46), 
AuthorityList_3 int(20), 
SortNo_4 int(3), 
HierarchyName_4 VARCHAR(46), 
AuthorityList_4 int(20), 
SortNo_5 int(3), 
HierarchyName_5 VARCHAR(46), 
AuthorityList_5 int(20), 
SortNo_6 int(3), 
HierarchyName_6 VARCHAR(46), 
AuthorityList_6 int(20), 
SortNo_7 int(3), 
HierarchyName_7 VARCHAR(46), 
AuthorityList_7 int(20), 
SortNo_8 int(3), 
HierarchyName_8 VARCHAR(46), 
AuthorityList_8 int(20), 
SortNo_9 int(3), 
HierarchyName_9 VARCHAR(46), 
AuthorityList_9 int(20), 
SortNo_10 int(3), 
HierarchyName_10 VARCHAR(46), 
AuthorityList_10 int(20), 
SortNo_11 int(3), 
HierarchyName_11 VARCHAR(46), 
AuthorityList_11 int(20), 
SortNo_12 int(3), 
HierarchyName_12 VARCHAR(46), 
AuthorityList_12 int(20), 
SortNo_13 int(3), 
HierarchyName_13 VARCHAR(46), 
AuthorityList_13 int(20), 
SortNo_14 int(3), 
HierarchyName_14 VARCHAR(46), 
AuthorityList_14 int(20), 
SortNo_15 int(3), 
HierarchyName_15 VARCHAR(46), 
AuthorityList_15 int(20),
`UPDATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`FreeCompanyId`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;