#ifndef SAPPHIRE_CHARACONNECTION_H
#define SAPPHIRE_CHARACONNECTION_H

#include "DbConnection.h"

namespace Core
{
namespace Db
{
class DbConnectionInfo;

enum CharaDbStatements : uint32_t
{
   CHARA_SEL,
   CHARA_SEL_MINIMAL,
   CHARA_SEARCHINFO_SEL,
   CHARA_QUEST_SEL,
   CHARA_INS,
   CHARA_UP,
   CHARA_UP_NAME,
   CHARA_UP_HPMP,
   CHARA_UP_MODE,
   CHARA_UP_MOUNT,
   CHARA_UP_INVINCIBLE,
   CHARA_UP_CUSTOMIZE,
   CHARA_UP_MODELMAINWEAP,
   CHARA_UP_MODELSUBWEAP,
   CHARA_UP_MODELSYSWEAP,
   CHARA_UP_MODELEQUIP,
   CHARA_UP_EMOTEMODETYPE,
   CHARA_UP_FIRSTLOGINTIME,
   CHARA_UP_LANGUAGE,
   CHARA_UP_ISNEWGAME,
   CHARA_UP_ISNEWADV,
   CHARA_UP_TERRITORY,
   CHARA_UP_POS,
   CHARA_UP_CLASS,
   CHARA_UP_STATUS,
   CHARA_UP_TOTALPLAYTIME,
   CHARA_UP_HOMEPOINT,
   CHARA_UP_FAVOPOINT,
   CHARA_UP_TITLE,
   CHARA_UP_TITLELIST,
   CHARA_UP_ACHIEVEMENTS,
   CHARA_UP_AETHERYTE,
   CHARA_UP_HOWTO,
   CHARA_UP_MINIONS,
   CHARA_UP_MOUNTS,
   CHARA_UP_GEARSET,
   CHARA_UP_CONFIGFLAGS,
   CHARA_UP_QUESTCOMPLETE,
   CHARA_UP_OPENINGSEQ,
   CHARA_UP_QUESTTRACKING,
   CHARA_UP_GRANDCOMPANY,
   CHARA_UP_GRANDCOMPANYRANKS,
   CHARA_UP_DISCOVERY,
   CHARA_UP_GMRANK,
   CHARA_UP_EQUIPDISPLAYFLAGS,
   CHARA_UP_UNLOCKS,
   CHARA_UP_CFPENATLY,
   CHARA_SEARCHINFO_INS,
   CHARA_SEARCHINFO_UP_SELECTCLASS,
   CHARA_SEARCHINFO_UP_SELECTREGION,
   CHARA_SEARCHINFO_UP_SEARCHCOMMENT,

   CHARA_QUEST_INS,
   CHARA_QUEST_UP,
   CHARA_QUEST_DEL,

   CHARA_CLASS_SEL,
   CHARA_CLASS_INS,
   CHARA_CLASS_UP,
   CHARA_CLASS_DEL,

   CHARA_ITEMINV_INS,

   CHARA_ITEMGLOBAL_INS,

   MAX_STATEMENTS
};

class  CharaDbConnection : public DbConnection
{
public:
   using Statements = CharaDbStatements;

   CharaDbConnection( ConnectionInfo& connInfo );
   CharaDbConnection( Core::LockedWaitQueue< boost::shared_ptr< Operation > >* q, ConnectionInfo &connInfo );

   ~CharaDbConnection();

   void doPrepareStatements() override;

};

}
}

#endif //SAPPHIRE_CHARACONNECTION_H
